# Generated by Django 4.1.5 on 2023-07-20 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('title', models.CharField(max_length=225, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=110, verbose_name='Описание')),
                ('type', models.CharField(choices=[('программирование', 'Программирование'), ('дизайн', 'Дизайн'), ('маркетинг', 'Маркетинг')], max_length=100, verbose_name='Выберите категорию')),
                ('vote_total', models.IntegerField(blank=True, default=0, null=True)),
                ('vote_ratio', models.IntegerField(blank=True, default=0, null=True)),
                ('preview', models.ImageField(blank=True, null=True, upload_to='previews', verbose_name='Добавить заставку')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(blank=True, default='Ваш Аккаунт', max_length=200, null=True, verbose_name='Ваше Имя и Фамилия')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Никнейм пользователя')),
                ('email', models.EmailField(blank=True, max_length=300, null=True, verbose_name='Ваша электронная почта')),
                ('profile_image', models.ImageField(blank=True, default='profiles/account.png', null=True, upload_to='profiles/', verbose_name='Фотография профиля')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('teacher', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('title', models.CharField(blank=True, max_length=225, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='movies')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('father', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainmenu.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainmenu.profile'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('body', models.TextField(blank=True, null=True)),
                ('value', models.CharField(choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainmenu.course')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainmenu.profile')),
            ],
            options={
                'unique_together': {('owner', 'course')},
            },
        ),
    ]
