# Generated by Django 4.1.5 on 2023-01-22 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True)),
                ('file', models.FileField(upload_to='movies')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Никнейм пользователя')),
                ('email', models.EmailField(blank=True, max_length=300, null=True, verbose_name='Ваша электронная почта')),
                ('profile_image', models.ImageField(blank=True, default='profiles/account.png', null=True, upload_to='profiles/', verbose_name='Фотография профиля')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('программирование', 'Программирование'), ('дизайн', 'Дизайн'), ('маркетинг', 'Маркетинг')], max_length=100)),
                ('preview', models.ImageField(blank=True, null=True, upload_to='previews')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainmenu.profile')),
                ('videos', models.ManyToManyField(to='mainmenu.video')),
            ],
        ),
    ]
