# Generated by Django 4.1.5 on 2023-01-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='teacher',
            field=models.BooleanField(default=False),
        ),
    ]
