# Generated by Django 4.1.5 on 2023-02-03 07:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0003_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('body', models.TextField(blank=True, null=True)),
                ('value', models.CharField(choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainmenu.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainmenu.course')),
            ],
            options={
                'unique_together': {('owner', 'project')},
            },
        ),
    ]
