# Generated by Django 4.1.5 on 2023-02-17 06:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0008_video_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='videos',
            field=models.ManyToManyField(blank=True, null=True, to='mainmenu.video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
