# Generated by Django 4.1.5 on 2023-02-20 05:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0010_alter_video_id_alter_video_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='owner',
        ),
        migrations.AlterField(
            model_name='course',
            name='videos',
            field=models.ManyToManyField(to='mainmenu.video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
