# Generated by Django 4.1.5 on 2023-02-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0011_remove_video_owner_alter_course_videos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='videos',
            field=models.ManyToManyField(blank=True, to='mainmenu.video'),
        ),
    ]
