# Generated by Django 4.1.5 on 2023-02-20 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0012_alter_course_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainmenu.course'),
        ),
    ]
