# Generated by Django 4.2.5 on 2023-10-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(default='avatars/profile.png', upload_to='avatars/', verbose_name='Аватарка'),
        ),
    ]
