# Generated by Django 4.2.5 on 2023-09-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='preview',
            new_name='thumbnail',
        ),
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='views'),
        ),
    ]
