# Generated by Django 4.2.5 on 2023-10-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='ID',
            new_name='id',
        ),
    ]
