# Generated by Django 4.2.5 on 2023-09-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='shapka',
            field=models.ImageField(blank=True, default=None, max_length=512, null=True, upload_to='shapki/', verbose_name='Шапка Профиля'),
        ),
    ]
